[package]
name = "zombie_runner_bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7", features = ["wayland", "dynamic"] }
bevy_rapier2d = "0.14.1"
